class_name: "MultilayerModel"
trainable: true
beta: 0
ckpt: null
params:
  channels: ${data.bands}
  ssl: ${data.ssl}
  n_ssl: ${data.n_ssl}
  ckpt: ${model.ckpt} 
  layers:
    l0:
      name: "LowRankSCLayer"
      params:
        patch_side: 1
        K: 12
        rank: 1
        code_size: 64
        stride: 1
        input_centering: 1
        patch_centering: 0
        tied: "D"
        init_method: "kaiming_uniform"
        lbda_init: 0.001
        lbda_mode: "MC"
        beta: ${model.beta}
        ssl: ${data.ssl}
    l1:
      name: "LowRankSCLayer"
      params:
        patch_side: 5
        K: 5
        rank: 3
        code_size: 1024
        stride: 1
        input_centering: 0
        patch_centering: 1
        tied: "D"
        init_method: "kaiming_uniform"
        lbda_init: 0.001
        lbda_mode: "MC"
        beta: 0
        ssl: 0

  base:
    optimizer: ${optim.optimizer}
    lr_scheduler: ${optim.scheduler}
    block_inference:
      use_bi: true
      block_size: 256
      overlap: 6
      padding: "reflect"
backtracking:
  monitor: "val_mpsnr"
  mode: "max"
  dirpath: "backtracking"
  period: 5
  div_thresh: 4
  dummy: False
  lr_decay: 0.8
id: T3SC_${data.name}_${noise.id}_beta${model.beta}_ssl${data.ssl}_seed${seed}
