name: PinkNoise
params:
  ratio_bands: 0.33
  alpha: 1
  noise_scale: 1.0
  sigma: 25
  seed: ${seed}
noise_level: ${noise.params.sigma}
id: ${noise.name}-a${noise.params.alpha}-s${noise.params.sigma}-i${noise.params.noise_scale}
